version: '3.8'

services:
  node-server-3000:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always
    networks:
      - app_network  # Liên kết với mạng app_network

  node-server-3001:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
    restart: always
    networks:
      - app_network  # Liên kết với mạng app_network

  node-server-3002:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3002
    restart: always
    networks:
      - app_network  # Liên kết với mạng app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - node-server-3000
      - node-server-3001
      - node-server-3002
    networks:
      - app_network  # Liên kết với mạng app_network

networks:
  app_network: 
    driver: bridge  # Địn
