
services:
  node-server-3000:
    build: .
    ports:
      - "3001:3005"
    environment:
      - PORT=3001
    restart: always
    networks:
      - app_network

  node-server-3001:
    build: .
    ports:
      - "3002:3005"
    environment:
      - PORT=3002
    restart: always
    networks:
      - app_network

  node-server-3002:
    build: .
    ports:
      - "3003:3005"
    environment:
      - PORT=3003
    restart: always
    networks:
      - app_network

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - node-server-3000
  #     - node-server-3001
  #     - node-server-3002
  #   networks:
  #     - app_network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5673:5673"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   networks:
  #     - app_network
    
networks:
  app_network:
    external: true


