version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80" # Host port mapped to container port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom NGINX config
    networks:
      - app_network

networks:
  app_network:
    external: true # Use your existing network
